-- 修正版本：移除重複姓名、改用外鍵關聯、日期改用正確型態
CREATE TABLE 使用者 (
  使用者ID SERIAL PRIMARY KEY,
  姓名 VARCHAR(50) NOT NULL
);

CREATE TABLE 用藥時程 (
  時程ID SERIAL PRIMARY KEY,
  使用者ID INTEGER NOT NULL REFERENCES 使用者(使用者ID),
  藥名 VARCHAR(50) NOT NULL,
  劑量 VARCHAR(20) NOT NULL
);

CREATE TABLE 服藥紀錄 (
  紀錄ID SERIAL PRIMARY KEY,
  時程ID INTEGER NOT NULL REFERENCES 用藥時程(時程ID),
  服用日期時間 TIMESTAMP NOT NULL,
  狀態 VARCHAR(10) NOT NULL DEFAULT '未服用'
);
